[Note: The Travis configuration below does not apply to all SSL projects.  For
instance, a project might opt to store tests in a different directory, so the
after_success entry below will differ.  Please modify the text accordingly
before incorporating it into your project.]


language: python
dist: trusty
sudo: false
cache: pip
python: 3.6

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py36

before_script:
  - pip install pylint bandit tox

script:
  - pylint tuf
  - bandit -r tuf
  - tox

after_success:
  - cd tests
  - coveralls
  - cd -

branches:
  only:
    - develop
    - pylint
    - bandit
